        globalThis.__SC_V2_CREATE_LIST_FORM_METHODS__ = ({ cfg }) => {
          const createManagedFormMethods = globalThis.__SC_V2_CREATE_MANAGED_FORM_METHODS__;
          const { getConfigState } = globalThis.__SC_V2_RUNTIME_HELPERS__;
          const getScopedFormConfig = (scope) => cfg?.forms?.[scope] || null;

          return createManagedFormMethods({
            tokenStoreKey: '__remoteRequestTokens',
            dependencyLockStoreKey: '__dependencyResetLocks',
            methodNames: {
              getFormRef: 'getFormRef',
              validateForm: 'validateForm',
              clearFormValidate: 'clearFormValidate',
              getFormModel: 'getFormModel',
              setFormModel: 'setFormModel',
              initializeFormModel: 'initializeFormModel',
              setFormPathValue: 'setFormPathValue',
              getOptionState: 'getOptionState',
              getOptionLoadingState: 'getOptionLoadingState',
              getOptionLoadedState: 'getOptionLoadedState',
              getUploadFileState: 'getUploadFileState',
              getPickerState: 'getPickerState',
              initializePickerState: 'initializePickerState',
              setUploadFileList: 'setUploadFileList',
              setFieldOptions: 'setFieldOptions',
              getFieldOptions: 'getFieldOptions',
              getLinkageConfig: 'getLinkageConfig',
              clearLinkageTargets: 'clearLinkageTargets',
              applyFormLinkage: 'applyFormLinkage',
              nextRemoteRequestToken: 'nextRemoteRequestToken',
              isLatestRemoteRequestToken: 'isLatestRemoteRequestToken',
              setDependencyResetSuspended: 'setDependencyResetSuspended',
              isDependencyResetSuspended: 'isDependencyResetSuspended',
              withDependencyResetSuspended: 'withDependencyResetSuspended',
              resetRemoteFieldState: 'resetRemoteFieldState',
              registerFormDependencies: 'registerFormDependencies',
              reloadDependentFieldOptions: 'reloadDependentFieldOptions',
              initializeFormOptions: 'initializeFormOptions',
              loadFormFieldOptions: 'loadFormFieldOptions',
              initializeUploadFiles: 'initializeUploadFiles',
              handleUploadBefore: 'handleUploadBefore',
              handleUploadSuccess: 'handleUploadSuccess',
              handleUploadError: 'handleUploadError',
              handleUploadRemove: 'handleUploadRemove',
              handleUploadExceed: 'handleUploadExceed',
              handleUploadPreview: 'handleUploadPreview'
            },
            getFormConfig: (scope) => getScopedFormConfig(scope),
            getRefName: (scope) => getScopedFormConfig(scope)?.ref || null,
            getFormModel: (vm, scope) => getConfigState(vm, getScopedFormConfig(scope), 'modelVar', 'modelPath'),
            getOptionState: (vm, scope) => getConfigState(vm, getScopedFormConfig(scope), 'optionStateVar', 'optionStatePath', true),
            getOptionLoadingState: (vm, scope) => getConfigState(vm, getScopedFormConfig(scope), 'optionLoadingVar', 'optionLoadingPath', true),
            getOptionLoadedState: (vm, scope) => getConfigState(vm, getScopedFormConfig(scope), 'optionLoadedVar', 'optionLoadedPath', true),
            getUploadFileState: (vm, scope) => getConfigState(vm, getScopedFormConfig(scope), 'uploadFilesVar', 'uploadFilesPath', true),
            getPickerState: (vm, scope) => getConfigState(vm, getScopedFormConfig(scope), 'pickerStateVar', 'pickerStatePath', true),
            getFormEvents: (scope) => getScopedFormConfig(scope)?.events || {},
            getArrayGroups: (scope) => getScopedFormConfig(scope)?.arrayGroups || [],
            getRemoteOptionsMap: (scope) => getScopedFormConfig(scope)?.remoteOptions || {},
            getRemoteOptionPaths: (scope) => getScopedFormConfig(scope)?.remoteOptionPaths || [],
            getSelectOptionsMap: (scope) => getScopedFormConfig(scope)?.selectOptions || {},
            getPickersMap: (scope) => getScopedFormConfig(scope)?.pickers || {},
            getPickerPaths: (scope) => getScopedFormConfig(scope)?.pickerPaths || [],
            getLinkagesMap: (scope) => getScopedFormConfig(scope)?.linkages || {},
            getUploadsMap: (scope) => getScopedFormConfig(scope)?.uploads || {},
            getUploadPaths: (scope) => getScopedFormConfig(scope)?.uploadPaths || []
          });
        };
